apiVersion: v1 
kind: Service
metadata:
  name: backend
spec:
  selector:
    #this way it target the deplyment spec
    app: second-app-label
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080 #the porn inside the container
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443 #multiple ports can be exported
  type: LoadBalancer
    
  
